id: I04B2D54D
default_language: en-us
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:20:20.643744+00:00
last_modified: 2022-12-14 18:20:20.643750+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-046-002
  eft-text-version: 1.3.4 2020
  title: Toh_96-The_Miraculous_Play_of_Manjusri-v2
bases:
  D2BF:
    source_metadata: null
    order: 1
    base_file: D2BF.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
